### ISSUE TITLE
Does not export all fragments

### ISSUE THREAD

**Issue by pa-0** [tomasmark79/MassCode2Md#1]
In massCode, tabs can be created inside snippets, essentially allowing mutliple snippets under one heading, called fragments.  masscode2md only exports one of those fragments for each snippet that contains multiple. For example for the following snippet, containing three fragmens, only the one titled "Get FilePath or Domain" is extracted:

![image](https://github.com/user-attachments/assets/5828d52e-0c36-44c7-be41-d6285723ad22)

**Comment by tomasmark79** [comment]
Hello 🙂

Thank you for your feedback and for reporting the bug.

I have fixed the issue, and now the fragments (tabs) are correctly included within the collection of backups to Markdown files.

https://github.com/tomasmark79/MassCode2Md/releases/tag/v0.0.2

**Comment by pa-0** [comment]
🙏 🙏 🙏  this is a super useful tool that fills a much needed gap in passcode functionality by the way, so thank you for sharing it
